---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: attraction-sync
spec:
  schedule: '*/15 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 101
            runAsGroup: 101
          containers:
            - name: telegram
              image: ghcr.io/christopherjmiller/tpl-passholder
              resources:
                requests:
                  memory: 100Mi
                  cpu: 100m
                limits:
                  memory: 100Mi
                  cpu: 100m
              securityContext:
                readOnlyRootFilesystem: true
                runAsUser: 101
                runAsGroup: 101
              env:
                - name: MODE
                  value: REFRESH
              envFrom:
                - secretRef:
                    name: tpl-secrets
